name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Print path of job.yml
        run: |
         realpath ./src/job.yml
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Install Azure ML CLI Extension
        run: |
          az extension add --name azure-cli-ml
      - name: Update Azure CLI and ML Extension
        run: |
          az extension remove -n azure-cli-ml
          az extension add -n ml -y
      - name: Verify Azure ML CLI Extension
        run: |
          az extension list
          az ml --help
      - name: Login to Azure
        run: |
          az login --service-principal \
            --username ${{ fromJson(secrets.AZURE_CREDENTIALS).appId }} \
            --password ${{ fromJson(secrets.AZURE_CREDENTIALS).password }} \
            --tenant ${{ fromJson(secrets.AZURE_CREDENTIALS).tenant }}
      - name: Submit Azure ML Job
        run: |
          az ml job create --file ../src/job.yml --resource-group RG01 --workspace-name amldemo
