name: Azure ML Job

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Add Azure ML Extension
      run: |
        az extension add --name ml

    - name: Run Azure ML Job
      run: |
        cd src
        az ml job create --file job.yml --web --resource-group RG01 --workspace-name amldemo
