name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Install Azure ML CLI extension
      run: az extension add --name azure-cli-ml

    - name: Verify Azure ML CLI Extension
      run: |
        az extension list
        az ml --help

    - name: Login to Azure
      run: |
        az login --service-principal \
          --username ${{ secrets.AZURE_CREDENTIALS.appId }} \
          --password ${{ secrets.AZURE_CREDENTIALS.password }} \
          --tenant ${{ secrets.AZURE_CREDENTIALS.tenant }}

    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file /src/job.yml
