name: Trigger Azure ML Job
on:
  workflow_dispatch:

jobs:
  run-aml-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Install Azure ML CLI extension
        run: az extension add --name azure-cli-ml

      - name: Login to Azure
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: az login --service-principal --username ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }} --password ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }} --tenant ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}

      - name: Submit Azure ML Job
        run: |
          az ml job create --file mslearn-mlops\src\job.yml
